# -*- coding: utf-8 -*-
"""Another copy of languageID.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iw-twi0WaDnkD5D4kxt---mfbHvLeue

# Language Identification Using Traditional and LLM-Based Approaches

> **Group Members:**


*   Nada Fayez Alsuhaimi (ID: 4450787)
*   Rama Hamed Alhasainy (ID: 4450069)

*   Raneem Abdullah Almukhlifi (ID: 4452518)
*   Rehab Saad Alharbi (ID: 4451026)
"""

import pandas as pd
import re
import matplotlib.pyplot as plt
import nltk
from sklearn.model_selection import train_test_split

from google.colab import files
uploaded = files.upload()

# read the data and check it
df = pd.read_csv("dataset.csv")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print(df.head())

# keep only the languages we want
target = ['English', 'French', 'Russian', 'Spanish', 'Japanese']

df = df[df['language'].isin(target)]
print("After filtering:", df.shape)
print(df['language'].value_counts())

# clean the text by removing links, numbers, and symbols
def preprocess(text):
    text = str(text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = text.strip()
    return text
# remove texts that are too short
df['final_text'] = df['Text'].apply(preprocess)
df = df[df['final_text'].str.len() > 10]

print("After cleaning:", df.shape)

samples_per_lang = 1000
df = df.groupby('language').apply(
    lambda x: x.sample(min(len(x), samples_per_lang), random_state=7)
).reset_index(drop=True)

print("balance classes: ", df.shape)
print(df['language'].value_counts())

# split into train and test sets
train, test = train_test_split(
    df,
    test_size=0.2,
    stratify=df['language'],
    random_state=21
)

print("Training set:", len(train))
print("Test set:", len(test))

# plot how many samples we have per language
counts = df['language'].value_counts()
plt.figure(figsize=(8, 5))
counts.plot(kind='bar', color='royalblue', edgecolor='black')
plt.title('Samples per Language')
plt.xlabel('Language')
plt.ylabel('Count')
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

"""# Traditional Approach

#Bag of Words + Naive Bayes classifier (Base line)
"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

# spliting the train & the test data to x and y
x_train = train['final_text']
y_train = train['language']

x_test = test['final_text']
y_test = test['language']

#Build the model
clf= Pipeline(
    [
        # Character-level Bag of Words using CountVectorizer n-grams from 2 to 5
        ("vect", CountVectorizer(analyzer='char',ngram_range=(2,5))),
        # Multinomial Naive Bayes classifier
        ("multy NB", MultinomialNB()) #Naive Bayse
    ]
)

#Fitting the model
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""#TF-IDF + SVM Classifier


"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

clf2= Pipeline (
    [
        # TF-IDF feature extraction using n-grams 2 to 5
        ('vectorizer_tfidf',TfidfVectorizer(analyzer='char', ngram_range=(2,5))),

        # SVM classifier
        ('svm',LinearSVC(random_state=42,dual=False))
    ]
  )

clf2.fit(x_train,y_train)

y_pred=clf2.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""# LLMs-Based Approach"""

!pip install -U bitsandbytes
!pip install git+https://github.com/huggingface/accelerate.git
!pip install git+https://github.com/huggingface/transformers.git

from google.colab import userdata
from huggingface_hub import login

#login to Hugging Face
token ="your token her"
login(token=hf_token)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
# WE Chose ALLam model
model_name = "ALLaM-AI/ALLaM-7B-Instruct-preview"


bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True
)

tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token)
allam_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# create the prompt
def prompt(text):
    persona = "You are a professional linguistic AI assistant.\n"
    instruction = "Identify the language of the provided text.\n"
    context = "Your task is to analyze the text and output ONLY the language name.\n"
    data_format = "Choose only one from this list: [English, French, Russian, Spanish, Japanese].\n"
    tone = "The tone should be formal and extremely concise.\n"

    query = persona + instruction + context + data_format + tone + f"\nText to translate: {text}\nAnswer:"
    return query

import re
import os

#Function to get model prediction
def get_prediction(text):
    query = prompt(text)

 #Prepare inputs
    messages=[
        {"role": "user", "content": query},
    ]
    inputs = tokenizer.apply_chat_template(messages, tokenize=False)
    inputs = tokenizer(inputs, return_tensors='pt', return_token_type_ids=False)
    inputs = {k: v.to('cuda') for k, v in inputs.items()}

    #Generate response
    with torch.no_grad():
        response = allam_model.generate(
            **inputs,
            max_new_tokens=10,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    #Regex clean
    pattern = r"\[INST\].*?\[/INST\]"
    generated_translation = tokenizer.batch_decode(response, skip_special_tokens=True)[0]
    generated_translation = re.sub(pattern, "", generated_translation, flags=re.DOTALL)
    result = os.linesep.join([s for s in generated_translation.splitlines() if s])

    # Extract answer
    prediction = result.split("Answer:")[-1].strip().split('\n')[0]

    return prediction

from tqdm import tqdm
from sklearn.metrics import accuracy_score, classification_report

# Run model
tqdm.pandas(desc="download")
test["ai_prediction"] = test["Text"].progress_apply(get_prediction)

# Clean output
def extract_language(text):
    text = str(text).lower()
    languages = ['english', 'french', 'russian', 'spanish', 'japanese']
    for lang in languages:
        if lang in text:
            return lang.capitalize()
    return "Unknown"

test["ai_prediction_clean"] = test["ai_prediction"].apply(extract_language)

#Format labels
test["language"] = test["language"].astype(str).str.strip().str.capitalize()

#Evaluate and print results
print("Accuracy:", accuracy_score(test["language"], test["ai_prediction_clean"]))
print("\nClassification Report:\n", classification_report(test["language"], test["ai_prediction_clean"]))

"""# Evaluation and Comparative Analysis"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score
#Accuracy Score
traditional_acc = accuracy_score(test['language'], y_pred)
llm_acc = accuracy_score(test['language'], test['ai_prediction_clean'])

print(f"Traditional Model Accuracy: {traditional_acc:.4f}")
print(f"ALLAM LLM Accuracy: {llm_acc:.4f}")

comparison_df = pd.DataFrame({
    'Model': ['Traditional (SVM)', 'LLM (ALLaM)'],
    'Accuracy': [traditional_acc, llm_acc]
})

plt.figure(figsize=(8, 6))
ax = sns.barplot(x='Model', y='Accuracy', data=comparison_df, palette='viridis')
plt.title('Overall Performance: Traditional vs LLM', fontsize=14)
plt.ylim(0, 1.1)

for p in ax.patches:
    ax.annotate(f'{p.get_height():.2%}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.show()

from sklearn.metrics import classification_report, confusion_matrix
# Display metrics (Precision, Recall, F1-score)
print("\n" + "="*20 + " TRADITIONAL MODEL REPORT " + "="*20)
print(classification_report(test['language'], y_pred))

print("\n" + "="*20 + " ALLAM LLM REPORT " + "="*20)
print(classification_report(test['language'], test['ai_prediction_clean']))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
labels = sorted(test['language'].unique())
# Plot Confusion Matrix
cm_trad = confusion_matrix(test['language'], y_pred, labels=labels)
sns.heatmap(cm_trad, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels, ax=ax1)
ax1.set_title('Confusion Matrix: Traditional Approach')

cm_llm = confusion_matrix(test['language'], test['ai_prediction_clean'], labels=labels)
sns.heatmap(cm_llm, annot=True, fmt='d', cmap='Greens', xticklabels=labels, yticklabels=labels, ax=ax2)
ax2.set_title('Confusion Matrix: ALLaM LLM Approach')

plt.tight_layout()
plt.show()

# Error Analysis: LLM Incorrect vs. Traditional Model Correct
print("\n--- Samples where LLM was incorrect but Traditional was correct ---")
mismatch = test[(test['ai_prediction_clean'] != test['language']) & (y_pred == test['language'])]
print(mismatch[['Text', 'language', 'ai_prediction_clean']].head())